#!/bin/bash
# Copyright (c) Swarm Library Maintainers.
# SPDX-License-Identifier: MIT

set -e

if [[ -z "${1}" ]]; then
    echo "Usage: $0 <prometheus-config-file>"
    exit 1
fi

PROMETHEUS_SCRAPE_CONFIG_DIR=${PROMETHEUS_SCRAPE_CONFIG_DIR:-"/prometheus/scrape_configs"}

# Generate the global configuration file.
PROMETHEUS_SCRAPE_INTERVAL=${PROMETHEUS_SCRAPE_INTERVAL:-"1m"}
PROMETHEUS_SCRAPE_TIMEOUT=${PROMETHEUS_SCRAPE_TIMEOUT:-"10s"}
PROMETHEUS_EVALUATION_INTERVAL=${PROMETHEUS_EVALUATION_INTERVAL:-"1m"}

echo "==> Generating the global configuration file..."
cat <<EOF > "${1}"
global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL} # Set the scrape interval to every ${PROMETHEUS_SCRAPE_INTERVAL}. Default is every 1 minute.
  scrape_timeout: ${PROMETHEUS_SCRAPE_TIMEOUT} # scrape_timeout is set to the ${PROMETHEUS_SCRAPE_TIMEOUT}. The default is 10s.
  evaluation_interval: ${PROMETHEUS_EVALUATION_INTERVAL} # Evaluate rules every ${PROMETHEUS_EVALUATION_INTERVAL}. The default is every 1 minute.

scrape_config_files:
  - "${PROMETHEUS_SCRAPE_CONFIG_DIR}/*"
EOF
