#!/bin/bash
# Copyright (c) Swarm Library Maintainers.
# SPDX-License-Identifier: MIT

set -e

if [[ -z "${1}" ]]; then
    echo "Usage: $0 <prometheus-config-file>"
    exit 1
fi

# Alerting configuration with DNS-based service discovery
ALERTMANAGER_SERVICE_NAME=${INTERNAL_ALERTMANAGER_DNS_NAME}
ALERTMANAGER_SERVICE_PORT=${INTERNAL_ALERTMANAGER_SERVICE_PORT:-"9093"}
ALERTMANAGER_SERVICE_REFRESH_INTERVAL=${ALERTMANAGER_SERVICE_REFRESH_INTERVAL:-"30s"}

if [[ -z "${ALERTMANAGER_SERVICE_NAME}" ]]; then
    echo "==> Alerting is not enabled, skipping alerting configuration..."
    exit 0
fi

# Generate alerting configuration
echo "==> Generating alerting configuration for "${ALERTMANAGER_SERVICE_NAME}:${ALERTMANAGER_SERVICE_PORT}"..."
cat <<EOF > "${1}"
alerting:
  alertmanagers:
    - scheme: 'http'
      dns_sd_configs:
      - names: ['${ALERTMANAGER_SERVICE_NAME}']
        type: 'A'
        port: ${ALERTMANAGER_SERVICE_PORT}
        refresh_interval: '${ALERTMANAGER_SERVICE_REFRESH_INTERVAL}'
EOF

exit 0
